// <auto-generated />
namespace ZOGLAB.MMMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_IsofeDel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_IsofeDel));
        
        string IMigrationMetadata.Id
        {
            get { return "201812290907586_added_IsofeDel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
