// <auto-generated />
namespace ZOGLAB.MMMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mTomDelete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mTomDelete));
        
        string IMigrationMetadata.Id
        {
            get { return "201812241106511_mTomDelete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
