// <auto-generated />
namespace ZOGLAB.MMMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class units : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(units));
        
        string IMigrationMetadata.Id
        {
            get { return "201812240139093_units"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
