// <auto-generated />
namespace ZOGLAB.MMMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_BD_5_entities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_BD_5_entities));
        
        string IMigrationMetadata.Id
        {
            get { return "201812170535382_added_BD_5_entities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
