// <auto-generated />
namespace ZOGLAB.MMMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class test_SiteID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test_SiteID));
        
        string IMigrationMetadata.Id
        {
            get { return "201901040614528_test_SiteID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
